export const ROUTES = {
	APP: {
		ROOT: '/app',
		NEW_STUDENT: '/app/new-student',
		TRAININGS: '/app/trainings',
		REPORTING: '/app/reporting',
		REPORTING_DETAIL: '/app/reporting/detail',
		EXAMS: '/app/exams',
		EXAMS_DETAIL: '/app/exams/detail',
		EXAMS_RESULTS: '/app/exams/results',
		SUPPORT: '/app/support',
		SETTINGS: '/app/settings',
		STUDENT_CARD: '/app/student',
		DEBUG: '/app/debug',
		MORE: '/app/more',
		//
		SUB_NEW_STUDENT: 'new-student',
		SUB_TRAININGS: 'trainings',
		SUB_REPORTING: 'reporting',
		SUB_REPORTING_DETAIL: 'reporting/detail',
		SUB_EXAMS: 'exams',
		SUB_EXAMS_DETAIL: 'exams/detail',
		SUB_EXAMS_RESULTS: 'exams/results',
		SUB_SUPPORT: 'support',
		SUB_SETTINGS: 'settings',
		SUB_STUDENT: 'student',
		SUB_DEBUG: 'debug',
		SUB_MORE: 'more',
	},
	OUT_APP: {
		LOGIN_FLOW: '/login-flow',
		LOGIN: '/login',
		REGISTER: '/register',
		CONFIR_REGISTRATION_CODE: '/email-confirm',
		RESET_PASSWORD: '/reset-password',
		RESET_PASSWORD_CONFIRM: '/reset-password-confirm',

		SUB_CONFIR_REGISTRATION_CODE: 'email-confirm',
		SUB_LOGIN: 'login',
		SUB_REGISTER: 'register',
		SUB_RESET_PASSWORD: 'reset-password',
		SUB_RESET_PASSWORD_CONFIRM: 'reset-password-confirm',

		EXPORT_EXAM: '/export-exam',
		EXPORT_REPORT: '/export-report',
	},
};
