openapi: "3.0.0"
info:
  version: 1.0.0
  title: Bastard proxy api

paths:
  /api/proxy:

    patch:
      tags:
        - Proxy
      summary: Update a proxy
      description: Update a proxy

      parameters:
        - name: id
          in: query
          description: Id of the proxy
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchProxy"

      responses:
        "200":
          description: Proxy response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
    post:
      tags:
        - Proxy
      summary: Create a new proxy
      description: Create a new proxy

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProxy"

      responses:
        "201":
          description: Proxy response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

    get:
      tags:
        - Proxy
      summary: Get all proxies
      description: Get all proxies

      responses:
        "200":
          description: Proxy response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Proxy"

    delete:
      tags:
        - Proxy
      summary: Delete a proxy
      description: Delete a proxy

      parameters:
        - name: id
          in: query
          description: Id of the proxy
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Proxy response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

  /api/guard/{proxyId}:
    post:
      tags:
        - Guard
      summary: Enable guard
      description: Enable guard
      parameters:
        - in: path
          name: proxyId
          schema:
            type: string
          required: true
          description: Id of parent proxy

      requestBody:
         required: true
         content:
           application/json:
             schema:
               $ref: "#/components/schemas/NewGuard"

      responses:
        "200":
          description: Guard response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

    delete:
      tags:
        - Guard
      summary: Disable guard
      description: Disable guard
      parameters:
        - name: id
          in: query
          description: Id of the block
          required: true
          schema:
            type: string
        - in: path
          name: proxyId
          schema:
            type: string
          required: true
          description: Id of parent proxy

      responses:
        "200":
          description: Guard response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

    get:
      tags:
        - Guard
      summary: Get all guards
      description: Get all guards
      parameters:
        - in: path
          name: proxyId
          schema:
            type: string
          required: true
          description: Id of parent proxy

      responses:
        "200":
          description: Guard response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Guard"


  /api/block/{proxyId}:

      get:
        tags:
          - Block
        summary: Get all blocks
        description: Get all blocks

        parameters:
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        responses:
          "200":
            description: Block response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Block"
      delete:
        tags:
          - Block
        summary: Delete a block
        description: Delete a block

        parameters:
          - name: id
            in: query
            description: Id of the block
            required: true
            schema:
              type: string
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        responses:
          "200":
            description: Block response
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SuccessResponse"

      post:
        tags:
          - Block
        summary: Create a new block
        description: Create a new block

        parameters:
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewBlock"

        responses:
          "201":
            description: Block response
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SuccessResponse"

  /api/allow/{proxyId}:

      get:
        tags:
          - Allow
        summary: Get all allows
        description: Get all allows

        parameters:
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        responses:
          "200":
            description: Allow response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Allow"
      delete:
        tags:
          - Allow
        summary: Delete a allow
        description: Delete a allow

        parameters:
          - name: id
            in: query
            description: Id of the allow
            required: true
            schema:
              type: string
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        responses:
          "200":
            description: Allow response
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SuccessResponse"

      post:
        tags:
          - Allow
        summary: Create a new allow
        description: Create a new allow

        parameters:
          - in: path
            name: proxyId
            schema:
              type: string
            required: true
            description: Id of parent proxy

        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewAllow"

        responses:
          "201":
            description: Allow response
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SuccessResponse"



components:
  schemas:
    NewProxy:
      required:
        - source
        - target

      properties:
        source:
          type: string
        target:
          type: string

    PatchProxy:
      required:
        - cache
        - disable
      properties:
        disable:
          type: boolean
        cache:
          type: boolean

    Proxy:
      required:
        - id
        - createdAt
        - source
        - target
        - disable
        - cache 
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        source:
          type: string
        target:
          type: string
        disable:
          type: boolean
        cache:
          type: boolean  

    NewBlock:
      required:
        - ip

      properties:
        ip:
          type: string

    Block:
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        proxyId:
          type: string
        ip:
          type: string

    NewAllow:
      required:
        - ip

      properties:
        ip:
          type: string

    Allow:
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        proxyId:
          type: string
        ip:
          type: string

    SuccessResponse:
      required:
        - message

      properties:
        message:
          type: string
          description: Message of the response
          example: OK

    NewGuard:
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    Guard:
      required:
        - email
        - id
      properties:
        email:
          type: string
        id:
          type: string