// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Activity defines model for Activity.
type Activity struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Ip        *string    `json:"ip,omitempty"`
	ProxyId   *string    `json:"proxyId,omitempty"`
}

// ActivityIpAggregate defines model for ActivityIpAggregate.
type ActivityIpAggregate struct {
	Ip  string   `json:"ip"`
	Sum *float32 `json:"sum,omitempty"`
}

// ActivityIpTimeline defines model for ActivityIpTimeline.
type ActivityIpTimeline struct {
	CreatedAt time.Time `json:"createdAt"`
	Sum       float32   `json:"sum"`
}

// Allow defines model for Allow.
type Allow struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Ip        *string    `json:"ip,omitempty"`
	ProxyId   *string    `json:"proxyId,omitempty"`
}

// Block defines model for Block.
type Block struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Ip        *string    `json:"ip,omitempty"`
	ProxyId   *string    `json:"proxyId,omitempty"`
}

// NewAllow defines model for NewAllow.
type NewAllow struct {
	Ip string `json:"ip"`
}

// NewBlock defines model for NewBlock.
type NewBlock struct {
	Ip string `json:"ip"`
}

// NewGuard defines model for NewGuard.
type NewGuard struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// NewProxy defines model for NewProxy.
type NewProxy struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

// PatchProxy defines model for PatchProxy.
type PatchProxy struct {
	Cache   bool `json:"cache"`
	Disable bool `json:"disable"`
}

// Proxy defines model for Proxy.
type Proxy struct {
	Cache     bool      `json:"cache"`
	CreatedAt time.Time `json:"createdAt"`
	Disable   bool      `json:"disable"`
	Guard     bool      `json:"guard"`
	Id        string    `json:"id"`
	Source    string    `json:"source"`
	Target    string    `json:"target"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Message Message of the response
	Message string `json:"message"`
}

// GetApiActivityProxyIdTimelineIpParams defines parameters for GetApiActivityProxyIdTimelineIp.
type GetApiActivityProxyIdTimelineIpParams struct {
	// Ip Ip to filter
	Ip string `form:"ip" json:"ip"`
}

// DeleteApiAllowProxyIdParams defines parameters for DeleteApiAllowProxyId.
type DeleteApiAllowProxyIdParams struct {
	// Id Id of the allow
	Id string `form:"id" json:"id"`
}

// DeleteApiBlockProxyIdParams defines parameters for DeleteApiBlockProxyId.
type DeleteApiBlockProxyIdParams struct {
	// Id Id of the block
	Id string `form:"id" json:"id"`
}

// DeleteApiGuardProxyIdParams defines parameters for DeleteApiGuardProxyId.
type DeleteApiGuardProxyIdParams struct {
	// Id Id of the block
	Id string `form:"id" json:"id"`
}

// DeleteApiProxyParams defines parameters for DeleteApiProxy.
type DeleteApiProxyParams struct {
	// Id Id of the proxy
	Id string `form:"id" json:"id"`
}

// PatchApiProxyParams defines parameters for PatchApiProxy.
type PatchApiProxyParams struct {
	// Id Id of the proxy
	Id string `form:"id" json:"id"`
}

// PostApiAllowProxyIdJSONRequestBody defines body for PostApiAllowProxyId for application/json ContentType.
type PostApiAllowProxyIdJSONRequestBody = NewAllow

// PostApiBlockProxyIdJSONRequestBody defines body for PostApiBlockProxyId for application/json ContentType.
type PostApiBlockProxyIdJSONRequestBody = NewBlock

// PostApiGuardProxyIdJSONRequestBody defines body for PostApiGuardProxyId for application/json ContentType.
type PostApiGuardProxyIdJSONRequestBody = NewGuard

// PatchApiProxyJSONRequestBody defines body for PatchApiProxy for application/json ContentType.
type PatchApiProxyJSONRequestBody = PatchProxy

// PostApiProxyJSONRequestBody defines body for PostApiProxy for application/json ContentType.
type PostApiProxyJSONRequestBody = NewProxy

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all activities
	// (GET /api/activity/{proxyId})
	GetApiActivityProxyId(c *gin.Context, proxyId string)
	// Get all activities aggregated by ip
	// (GET /api/activity/{proxyId}/aggregate/ip)
	GetApiActivityProxyIdAggregateIp(c *gin.Context, proxyId string)
	// Get all activities timeline by ip
	// (GET /api/activity/{proxyId}/timeline/ip)
	GetApiActivityProxyIdTimelineIp(c *gin.Context, proxyId string, params GetApiActivityProxyIdTimelineIpParams)
	// Delete a allow
	// (DELETE /api/allow/{proxyId})
	DeleteApiAllowProxyId(c *gin.Context, proxyId string, params DeleteApiAllowProxyIdParams)
	// Get all allows
	// (GET /api/allow/{proxyId})
	GetApiAllowProxyId(c *gin.Context, proxyId string)
	// Create a new allow
	// (POST /api/allow/{proxyId})
	PostApiAllowProxyId(c *gin.Context, proxyId string)
	// Delete a block
	// (DELETE /api/block/{proxyId})
	DeleteApiBlockProxyId(c *gin.Context, proxyId string, params DeleteApiBlockProxyIdParams)
	// Get all blocks
	// (GET /api/block/{proxyId})
	GetApiBlockProxyId(c *gin.Context, proxyId string)
	// Create a new block
	// (POST /api/block/{proxyId})
	PostApiBlockProxyId(c *gin.Context, proxyId string)
	// Disable guard
	// (DELETE /api/guard/{proxyId})
	DeleteApiGuardProxyId(c *gin.Context, proxyId string, params DeleteApiGuardProxyIdParams)
	// Enable guard
	// (POST /api/guard/{proxyId})
	PostApiGuardProxyId(c *gin.Context, proxyId string)
	// Delete a proxy
	// (DELETE /api/proxy)
	DeleteApiProxy(c *gin.Context, params DeleteApiProxyParams)
	// Get all proxies
	// (GET /api/proxy)
	GetApiProxy(c *gin.Context)
	// Update a proxy
	// (PATCH /api/proxy)
	PatchApiProxy(c *gin.Context, params PatchApiProxyParams)
	// Create a new proxy
	// (POST /api/proxy)
	PostApiProxy(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiActivityProxyId operation middleware
func (siw *ServerInterfaceWrapper) GetApiActivityProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiActivityProxyId(c, proxyId)
}

// GetApiActivityProxyIdAggregateIp operation middleware
func (siw *ServerInterfaceWrapper) GetApiActivityProxyIdAggregateIp(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiActivityProxyIdAggregateIp(c, proxyId)
}

// GetApiActivityProxyIdTimelineIp operation middleware
func (siw *ServerInterfaceWrapper) GetApiActivityProxyIdTimelineIp(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiActivityProxyIdTimelineIpParams

	// ------------- Required query parameter "ip" -------------

	if paramValue := c.Query("ip"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument ip is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "ip", c.Request.URL.Query(), &params.Ip)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ip: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiActivityProxyIdTimelineIp(c, proxyId, params)
}

// DeleteApiAllowProxyId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiAllowProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiAllowProxyIdParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiAllowProxyId(c, proxyId, params)
}

// GetApiAllowProxyId operation middleware
func (siw *ServerInterfaceWrapper) GetApiAllowProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiAllowProxyId(c, proxyId)
}

// PostApiAllowProxyId operation middleware
func (siw *ServerInterfaceWrapper) PostApiAllowProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiAllowProxyId(c, proxyId)
}

// DeleteApiBlockProxyId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiBlockProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiBlockProxyIdParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiBlockProxyId(c, proxyId, params)
}

// GetApiBlockProxyId operation middleware
func (siw *ServerInterfaceWrapper) GetApiBlockProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiBlockProxyId(c, proxyId)
}

// PostApiBlockProxyId operation middleware
func (siw *ServerInterfaceWrapper) PostApiBlockProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiBlockProxyId(c, proxyId)
}

// DeleteApiGuardProxyId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiGuardProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiGuardProxyIdParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiGuardProxyId(c, proxyId, params)
}

// PostApiGuardProxyId operation middleware
func (siw *ServerInterfaceWrapper) PostApiGuardProxyId(c *gin.Context) {

	var err error

	// ------------- Path parameter "proxyId" -------------
	var proxyId string

	err = runtime.BindStyledParameterWithOptions("simple", "proxyId", c.Param("proxyId"), &proxyId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter proxyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiGuardProxyId(c, proxyId)
}

// DeleteApiProxy operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiProxy(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteApiProxyParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiProxy(c, params)
}

// GetApiProxy operation middleware
func (siw *ServerInterfaceWrapper) GetApiProxy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiProxy(c)
}

// PatchApiProxy operation middleware
func (siw *ServerInterfaceWrapper) PatchApiProxy(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchApiProxyParams

	// ------------- Required query parameter "id" -------------

	if paramValue := c.Query("id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", c.Request.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchApiProxy(c, params)
}

// PostApiProxy operation middleware
func (siw *ServerInterfaceWrapper) PostApiProxy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiProxy(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/activity/:proxyId", wrapper.GetApiActivityProxyId)
	router.GET(options.BaseURL+"/api/activity/:proxyId/aggregate/ip", wrapper.GetApiActivityProxyIdAggregateIp)
	router.GET(options.BaseURL+"/api/activity/:proxyId/timeline/ip", wrapper.GetApiActivityProxyIdTimelineIp)
	router.DELETE(options.BaseURL+"/api/allow/:proxyId", wrapper.DeleteApiAllowProxyId)
	router.GET(options.BaseURL+"/api/allow/:proxyId", wrapper.GetApiAllowProxyId)
	router.POST(options.BaseURL+"/api/allow/:proxyId", wrapper.PostApiAllowProxyId)
	router.DELETE(options.BaseURL+"/api/block/:proxyId", wrapper.DeleteApiBlockProxyId)
	router.GET(options.BaseURL+"/api/block/:proxyId", wrapper.GetApiBlockProxyId)
	router.POST(options.BaseURL+"/api/block/:proxyId", wrapper.PostApiBlockProxyId)
	router.DELETE(options.BaseURL+"/api/guard/:proxyId", wrapper.DeleteApiGuardProxyId)
	router.POST(options.BaseURL+"/api/guard/:proxyId", wrapper.PostApiGuardProxyId)
	router.DELETE(options.BaseURL+"/api/proxy", wrapper.DeleteApiProxy)
	router.GET(options.BaseURL+"/api/proxy", wrapper.GetApiProxy)
	router.PATCH(options.BaseURL+"/api/proxy", wrapper.PatchApiProxy)
	router.POST(options.BaseURL+"/api/proxy", wrapper.PostApiProxy)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW/jNhD9KwLbo7rOtjfdkrYIgqKt0Y/TwgdaGttsJZEhqc0agf57MaQo2SIlS924",
	"UdC92aI4H+/NPI7pZ5LyQvASSq1I8kxUeoCCmo+3qWYfmT7iZyG5AKkZmJVUAtWQ3Wr8suOyoJokJKMa",
	"vtGsABITfRRAEqK0ZOWe1DFhGb7rPxbBx0LyT8eH0Ja6jtvAHsTtfi9hTzX4MQ5YVlVx8rysii1IgkYl",
	"PFZMQkaSD7i3SWFz5u4PVkDOSngRRCZF0tm1G0w8ec6fFkfKXc7TvxcX1S/wNABX0JxfBxtrZCC7eUbu",
	"Kyoz3wgUlOXh3KhST1xml51YGyc7GpdrRMd3qXglUwj61FTuQV/22JhoN6DDNdXpYcBlStPDqcct5znQ",
	"El1mTNFtHlzst4Mx0u0wTmf7+xc1ORJiTPaOV39poJZfAH+WkfhcHnqEdEHHLW42UkTt9ypNQanfQAle",
	"qoCiFaAU3ZuFDFQqmdCMlyQhP9uFiO8ifYBIOgsxgU+0EAgS+fUnH8Re/M7+xvQpK3fc5My0MXBHlaYy",
	"i0x3R1QwEpOPIJUN4f27m3c3CBYXUOJiQr4zj7AB9MHEv6KCrWgj3avnRiZqXGrwPU/rHnRE8zxqtiAK",
	"xr6k+AIKDL5yK5g7DtaN8KBPSQvQIBVJPvTtPmSIlKASSm3TIZguSUyoJCYlLTBj0ZrrUNKygrg5kkMV",
	"scGXLfwm529vbkzp81JDaXKkQuQsNSms/lIY0POJPaahMBu/lrAjCflq1Q0Dq2YSWLVjQN1SSqWkRyuw",
	"58m6d7uqqO1JV1B5HAJZ0z0C180bG9w0wN+KuiN/ZcV3IplRuy+LtsfInPAT2G0HjAfxvyH6dKy6Cuch",
	"LuYVgW4GsfMamMCnm+Bel87YcyYizaMdyzVI5+axAnns/BiUFlsx7WR8nYJxfE8qF5z3zgU/gxx04Cj7",
	"wTyPaGT2eIpgl7GIcHmW3uPJ6IwG2fzcglmw2IxVTH/sCJUHwjZUGx5jbSGY7zjZjB8I+NrgyT6b5res",
	"9gawKe06xoeHq8+H4CpAyPdmco1oVMLTQPutuVocK48VKH3Hs+OLdUT7C7U+n5AxnNorhPeL6cQggX32",
	"nSZv8efzTE02e4Y12fwin63JzugXTZ5VCQbsi5rswHVVYC9NLmqy2TakyfNpfsOabAGboMmjfHi4+nxM",
	"0ORw+zWavChWrqLJDRWL0+RR5oME9tl3mmzugiZqsr1Iiuz10aAkm/vNL5L83xSCAXtQknuEuRq4b+//",
	"wgrwYznCc9P781l+a71vUZrU+8uhvEddn3HX9cLdll+cvxxdA82+bpYndvkZ+Z/X5a/ceCbxi7OQy9fx",
	"YOG6OAvhtuGrZ4f59ScR62nCJDKKhp+VD4egOj34gPwpMjpShuafptevwpeXn5O/0JYnQKNke4wFuL48",
	"dg7QbY+erv6vovszYH+/GNiD6PWhr+v6nwAAAP///oZCP+khAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
