/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Bastard proxy api
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  DeleteApiGuardProxyIdParams
} from '../model/deleteApiGuardProxyIdParams'
import type {
  NewGuard
} from '../model/newGuard'
import type {
  SuccessResponse
} from '../model/successResponse'



/**
 * Enable guard
 * @summary Enable guard
 */
export const postApiGuardProxyId = (
    proxyId: string,
    newGuard: NewGuard, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    
    return axios.post(
      `/api/guard/${proxyId}`,
      newGuard,options
    );
  }



export const getPostApiGuardProxyIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGuardProxyId>>, TError,{proxyId: string;data: NewGuard}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGuardProxyId>>, TError,{proxyId: string;data: NewGuard}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGuardProxyId>>, {proxyId: string;data: NewGuard}> = (props) => {
          const {proxyId,data} = props ?? {};

          return  postApiGuardProxyId(proxyId,data,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type PostApiGuardProxyIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGuardProxyId>>>
    export type PostApiGuardProxyIdMutationBody = NewGuard
    export type PostApiGuardProxyIdMutationError = AxiosError<unknown>

    /**
 * @summary Enable guard
 */
export const usePostApiGuardProxyId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGuardProxyId>>, TError,{proxyId: string;data: NewGuard}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getPostApiGuardProxyIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Disable guard
 * @summary Disable guard
 */
export const deleteApiGuardProxyId = (
    proxyId: string,
    params: DeleteApiGuardProxyIdParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    
    return axios.delete(
      `/api/guard/${proxyId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDeleteApiGuardProxyIdMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiGuardProxyId>>, TError,{proxyId: string;params: DeleteApiGuardProxyIdParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiGuardProxyId>>, TError,{proxyId: string;params: DeleteApiGuardProxyIdParams}, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiGuardProxyId>>, {proxyId: string;params: DeleteApiGuardProxyIdParams}> = (props) => {
          const {proxyId,params} = props ?? {};

          return  deleteApiGuardProxyId(proxyId,params,axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type DeleteApiGuardProxyIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiGuardProxyId>>>
    
    export type DeleteApiGuardProxyIdMutationError = AxiosError<unknown>

    /**
 * @summary Disable guard
 */
export const useDeleteApiGuardProxyId = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiGuardProxyId>>, TError,{proxyId: string;params: DeleteApiGuardProxyIdParams}, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getDeleteApiGuardProxyIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    