/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Bastard proxy api
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Activity
} from '../model/activity'
import type {
  ActivityIpAggregate
} from '../model/activityIpAggregate'
import type {
  ActivityIpTimeline
} from '../model/activityIpTimeline'
import type {
  GetApiActivityProxyIdTimelineIpParams
} from '../model/getApiActivityProxyIdTimelineIpParams'



/**
 * Get all activities aggregated by ip
 * @summary Get all activities aggregated by ip
 */
export const getApiActivityProxyIdAggregateIp = (
    proxyId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityIpAggregate[]>> => {
    
    return axios.get(
      `/api/activity/${proxyId}/aggregate/ip`,options
    );
  }


export const getGetApiActivityProxyIdAggregateIpQueryKey = (proxyId: string,) => {
    return [`/api/activity/${proxyId}/aggregate/ip`] as const;
    }

    
export const getGetApiActivityProxyIdAggregateIpQueryOptions = <TData = Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>, TError = AxiosError<unknown>>(proxyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiActivityProxyIdAggregateIpQueryKey(proxyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>> = ({ signal }) => getApiActivityProxyIdAggregateIp(proxyId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(proxyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiActivityProxyIdAggregateIpQueryResult = NonNullable<Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>>
export type GetApiActivityProxyIdAggregateIpQueryError = AxiosError<unknown>

/**
 * @summary Get all activities aggregated by ip
 */
export const useGetApiActivityProxyIdAggregateIp = <TData = Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>, TError = AxiosError<unknown>>(
 proxyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdAggregateIp>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiActivityProxyIdAggregateIpQueryOptions(proxyId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all activities timeline by ip
 */
export const getApiActivityProxyIdTimelineIp = (
    proxyId: string,
    params: GetApiActivityProxyIdTimelineIpParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityIpTimeline[]>> => {
    
    return axios.get(
      `/api/activity/${proxyId}/timeline/ip`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetApiActivityProxyIdTimelineIpQueryKey = (proxyId: string,
    params: GetApiActivityProxyIdTimelineIpParams,) => {
    return [`/api/activity/${proxyId}/timeline/ip`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiActivityProxyIdTimelineIpQueryOptions = <TData = Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>, TError = AxiosError<unknown>>(proxyId: string,
    params: GetApiActivityProxyIdTimelineIpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiActivityProxyIdTimelineIpQueryKey(proxyId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>> = ({ signal }) => getApiActivityProxyIdTimelineIp(proxyId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(proxyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiActivityProxyIdTimelineIpQueryResult = NonNullable<Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>>
export type GetApiActivityProxyIdTimelineIpQueryError = AxiosError<unknown>

/**
 * @summary Get all activities timeline by ip
 */
export const useGetApiActivityProxyIdTimelineIp = <TData = Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>, TError = AxiosError<unknown>>(
 proxyId: string,
    params: GetApiActivityProxyIdTimelineIpParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyIdTimelineIp>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiActivityProxyIdTimelineIpQueryOptions(proxyId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get all activities
 * @summary Get all activities
 */
export const getApiActivityProxyId = (
    proxyId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Activity[]>> => {
    
    return axios.get(
      `/api/activity/${proxyId}`,options
    );
  }


export const getGetApiActivityProxyIdQueryKey = (proxyId: string,) => {
    return [`/api/activity/${proxyId}`] as const;
    }

    
export const getGetApiActivityProxyIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiActivityProxyId>>, TError = AxiosError<unknown>>(proxyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiActivityProxyIdQueryKey(proxyId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiActivityProxyId>>> = ({ signal }) => getApiActivityProxyId(proxyId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(proxyId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiActivityProxyIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiActivityProxyId>>>
export type GetApiActivityProxyIdQueryError = AxiosError<unknown>

/**
 * @summary Get all activities
 */
export const useGetApiActivityProxyId = <TData = Awaited<ReturnType<typeof getApiActivityProxyId>>, TError = AxiosError<unknown>>(
 proxyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiActivityProxyId>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiActivityProxyIdQueryOptions(proxyId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



