/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Bastard proxy api
 * OpenAPI spec version: 1.0.0
 */

export interface Activity {
  createdAt?: string;
  id?: string;
  ip?: string;
  proxyId?: string;
}
