/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Bastard proxy api
 * OpenAPI spec version: 1.0.0
 */

export interface Proxy {
  cache: boolean;
  createdAt: string;
  disable: boolean;
  guard: boolean;
  id: string;
  source: string;
  target: string;
}
